version: '3.7'

services:
  queue:
    image: rabbitmq:3-management
    command: sh -c "echo [rabbitmq_management,rabbitmq_management_agent,rabbitmq_amqp1_0]. > /etc/rabbitmq/enabled_plugins && exec docker-entrypoint.sh rabbitmq-server"
    networks:
      - armonik-backend
    ports:
      - 127.0.0.1:5672:5672
      - 15672:15672
    healthcheck:
        test: rabbitmq-diagnostics check_port_connectivity
        interval: 10s
        timeout: 3s
        start_period: 10s
        retries: 10

  armonik.control.submitter:
    depends_on:
      queue:
        condition: service_healthy
    environment:
      - Amqp__User=guest
      - Amqp__Password=guest
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__MaxRetries=10
      - Amqp__LinkCredit=2

  armonik.control.metrics:
    environment:
      - Amqp__User=guest
      - Amqp__Password=guest
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__MaxRetries=10
      - Amqp__LinkCredit=2

  armonik.control.partitionmetrics:
    environment:
      - Amqp__User=guest
      - Amqp__Password=guest
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__MaxRetries=10
      - Amqp__LinkCredit=2

  armonik.compute.pollingagent0:
    depends_on:
      queue:
        condition: service_healthy
    environment:
      - Amqp__User=guest
      - Amqp__Password=guest      
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__MaxRetries=10
      - Amqp__LinkCredit=2

  armonik.compute.pollingagent1:
    depends_on:
      queue:
        condition: service_healthy
    environment:
      - Amqp__User=guest
      - Amqp__Password=guest
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__MaxRetries=10
      - Amqp__LinkCredit=2

  armonik.compute.pollingagent2:
    depends_on:
      queue:
        condition: service_healthy
    environment:
      - Amqp__User=guest
      - Amqp__Password=guest
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__MaxRetries=10
      - Amqp__LinkCredit=2
