version: '3.7'

services:
  queue:
    image: symptoma/activemq:5.16.3
    networks:
      - armonik-backend
    ports:
      - 5672:5672
      - 8161:8161
    volumes:
      - ./activemq/jetty.xml:/opt/activemq/conf/jetty.xml
      - ./activemq/activemq.xml:/opt/activemq/conf/activemq.xml
    healthcheck:
        test: ["CMD-SHELL", "curl -f -u admin:admin -s http://localhost:8161/api/jolokia/exec/org.apache.activemq:type=Broker,brokerName=localhost,service=Health/healthStatus -H Origin:http://localhost | grep Good || exit 1 && echo $$?"]
        interval: 10s
        timeout: 5s
        start_period: 20s
        retries: 5

  armonik.control.submitter:
    depends_on:
      queue:
        condition: service_healthy
    environment:
      - Amqp__User=admin
      - Amqp__Password=admin
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__MaxRetries=10
      - Amqp__LinkCredit=2

  armonik.control.metrics:
    environment:
      - Amqp__User=admin
      - Amqp__Password=admin
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__MaxRetries=10
      - Amqp__LinkCredit=2

  armonik.control.partitionmetrics:
    environment:
      - Amqp__User=admin
      - Amqp__Password=admin
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__MaxRetries=10
      - Amqp__LinkCredit=2

  armonik.compute.pollingagent0:
    depends_on:
      queue:
        condition: service_healthy
    environment:
      - Amqp__User=admin
      - Amqp__Password=admin
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__MaxRetries=10
      - Amqp__LinkCredit=2

  armonik.compute.pollingagent1:
    depends_on:
      queue:
        condition: service_healthy
    environment:
      - Amqp__User=admin
      - Amqp__Password=admin
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__MaxRetries=10
      - Amqp__LinkCredit=2

  armonik.compute.pollingagent2:
    depends_on:
      queue:
        condition: service_healthy
    environment:
      - Amqp__User=admin
      - Amqp__Password=admin
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__MaxRetries=10
      - Amqp__LinkCredit=2