version: '3.7'

services:
  queue:
    image: vromero/activemq-artemis:2.6.1
    environment:
      ENABLE_JMX_EXPORTER: "true"
      ARTEMIS_MIN_MEMORY: "1512M"
      ARTEMIS_MAX_MEMORY: "2000M"
      ARTEMIS_USERNAME: "guest"
      ARTEMIS_PASSWORD: "guest"
    networks:
      - armonik-backend
    ports:
      - 5672:5672
      - 8161:8161

  armonik.control.submitter:
    depends_on:
      queue:
        condition: service_started
    environment:
      - Amqp__User=guest
      - Amqp__Password=guest
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__MaxRetries=10
      - Amqp__LinkCredit=2

  armonik.control.metrics:
    environment:
      - Amqp__User=guest
      - Amqp__Password=guest
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__MaxRetries=10
      - Amqp__LinkCredit=2

  armonik.control.partitionmetrics:
    environment:
      - Amqp__User=guest
      - Amqp__Password=guest
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__MaxRetries=10
      - Amqp__LinkCredit=2

  armonik.compute.pollingagent0:
    depends_on:
      queue:
        condition: service_started
    environment:
      - Amqp__User=guest
      - Amqp__Password=guest
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__MaxRetries=10
      - Amqp__LinkCredit=2

  armonik.compute.pollingagent1:
    depends_on:
      queue:
        condition: service_started
    environment:
      - Amqp__User=guest
      - Amqp__Password=guest
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__MaxRetries=10
      - Amqp__LinkCredit=2

  armonik.compute.pollingagent2:
    depends_on:
      queue:
        condition: service_started
    environment:
      - Amqp__User=guest
      - Amqp__Password=guest
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__MaxRetries=10
      - Amqp__LinkCredit=2