version: '3.4'

services:
  armonik.core.compute.pollingagent:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "1080"

  armonik.core.control.submitter:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:1080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  armonik.core.control.metrics:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:1080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro


  armonik.samples.htcmock.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "1080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
