version: '3.4'

services:
  armonik.core.compute.pollingagent:
    image: ${DOCKER_REGISTRY-}armonikcorecomputepollingagent
    build:
      context: ../..
      dockerfile: Compute/PollingAgent/src/Dockerfile
    volumes:
      - socket_vol:/cache
    environment:
      - Components__TableStorage=ArmoniK.Adapters.MongoDB.TableStorage
      - MongoDB__Host=database
      - MongoDB__Port=27017
      - MongoDB__DatabaseName=database
      - MongoDB__TableStorage__PollingDelayMin=00:00:01
      - MongoDB__TableStorage__PollingDelayMax=00:00:10
      - Components__ObjectStorage=ArmoniK.Adapters.Redis.ObjectStorage
      - Redis__EndpointUrl=object:6379
      - Components__QueueStorage=ArmoniK.Adapters.Amqp.QueueStorage
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__User=admin
      - Amqp__Password=admin
      - Amqp__MaxRetries=10
      - Serilog__MinimumLevel=${LOGGING_LEVEL:-Information}
      - Zipkin__Uri=http://zipkin:9411/api/v2/spans
    depends_on:
      - database
      - object
      - queue
      - fluentbit
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
    networks:
      - armonik-net

  armonik.core.control.submitter:
    image: ${DOCKER_REGISTRY-}armonikcorecontrolsubmitter
    build:
      context: ../..
      dockerfile: Control/Submitter/src/Dockerfile
    environment:
      - Components__TableStorage=ArmoniK.Adapters.MongoDB.TableStorage
      - MongoDB__Host=database
      - MongoDB__Port=27017
      - MongoDB__DatabaseName=database
      - MongoDB__TableStorage__PollingDelayMin=00:00:01
      - MongoDB__TableStorage__PollingDelayMax=00:00:10
      - Components__ObjectStorage=ArmoniK.Adapters.Redis.ObjectStorage
      - Redis__EndpointUrl=object:6379
      - Components__QueueStorage=ArmoniK.Adapters.Amqp.QueueStorage
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__User=admin
      - Amqp__Password=admin
      - Amqp__MaxRetries=10
      - Serilog__MinimumLevel=${LOGGING_LEVEL:-Information}
      - Zipkin__Uri=http://zipkin:9411/api/v2/spans
    depends_on:
      - fluentbit
      - database
      - object
      - queue
      - zipkin
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
    networks:
      - armonik-net

  armonik.core.control.metrics:
    image: ${DOCKER_REGISTRY-}armonikcorecontrolmetrics
    build:
      context: ../..
      dockerfile: Control/Metrics/src/Dockerfile
    environment:
      - Metrics__ApiVersion=TestApiVersion
      - Metrics__DescribedObject__ApiVersion=TestApiVersion
      - Metrics__DescribedObject__Name=metrics-exporter
      - Metrics__DescribedObject__Namespace=armonik
      - Components__TableStorage=ArmoniK.Adapters.MongoDB.TableStorage
      - MongoDB__Host=database
      - MongoDB__Port=27017
      - MongoDB__DatabaseName=database
      - MongoDB__TableStorage__PollingDelayMin=00:00:01
      - MongoDB__TableStorage__PollingDelayMax=00:00:10
      - Components__ObjectStorage=ArmoniK.Adapters.Redis.ObjectStorage
      - Redis__EndpointUrl=object:6379
      - Components__QueueStorage=ArmoniK.Adapters.Amqp.QueueStorage
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__User=admin
      - Amqp__Password=admin
      - Amqp__MaxRetries=10
      - Serilog__MinimumLevel=${LOGGING_LEVEL:-Information}
    depends_on:
      - database
      - object
      - queue
      - fluentbit
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
    networks:
      - armonik-net

  database:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - armonik-net

  object:
    image: redis:bullseye
    command: redis-server
    expose:
      - 6379
    networks:
      - armonik-net

  queue:
    image: symptoma/activemq:5.16.3
    ports:
      - 127.0.0.1:5672:5672
      - 127.0.0.1:8161:8161
    networks:
      - armonik-net

  fluentbit:
    image: fluent/fluent-bit:latest
    volumes:
      - ../fluent-bit/etc:/fluent-bit/etc
    ports:
      - 24224:24224
      - 24224:24224/udp
    depends_on:
      - seq
    networks:
      - armonik-net

  seq:
    image: datalust/seq:latest
    restart: always
    ports:
      - 80:80
      - 5341:5341
    environment:
      - ACCEPT_EULA=Y
    networks:
      - armonik-net

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    networks:
      - armonik-net

  armonik.samples.htcmock.server:
    image: ${DOCKER_REGISTRY-}armoniksampleshtcmockserver
    ports:
      - 1080:1080
    build:
      context: ../..
      dockerfile: Tests/HtcMock/Server/src/Dockerfile
    volumes:
      - socket_vol:/cache
    environment:
      - Serilog__Properties__Application=ArmoniK.Compute.Worker
      - Serilog__MinimumLevel=${LOGGING_LEVEL:-Information}
    depends_on:
      - database
      - object
      - queue
      - fluentbit
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
    networks:
      - armonik-net

  armonik.samples.htcmock.client:
    image: ${DOCKER_REGISTRY-}armoniksampleshtcmockclient
    build:
      context: ../..
      dockerfile: Tests/HtcMock/Client/src/Dockerfile
    environment:
      - Grpc__Endpoint=http://armonik.core.control.submitter:1080
      - SLEEP_BEFORE_LAUNCH=10000
    depends_on:
      - database
      - object
      - queue
      - fluentbit
      - armonik.samples.htcmock.server
      - armonik.core.control.submitter
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
    networks:
      - armonik-net

volumes:
  socket_vol: {}


networks:
  armonik-net:
    name: armonik-net
